### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by dakur** [mklkj/tinymce-i18n#3]
Hi, how should I use the languages in v5? There is folder `langs5`, but there is no `en_*` file in there. In `langs`, there is. Should I use it from there? Thanks.

**Comment by mklkj** [comment]
Hi @dakur, this package is only a copy of the files available on https://www.tiny.cloud/get-tiny/language-packages/.
According to docs https://www.tiny.cloud/docs/configure/localization/, if you want to use `en_US` - no need to perform any additional actions. But if you really need to use others `en_*` translations - files in `langs` should be mostly compatible with v5

**Comment by dakur** [comment]
Ok, thank you for your answer!
