### ISSUE TITLE
Different files from npm and tiny.cloud download link

### ISSUE THREAD

**Issue by yunay** [mklkj/tinymce-i18n#4]
Lang bg_BG is not same downloaded from npm and from https://www.tiny.cloud/get-tiny/language-packages/
File from npm has not translated labels. 
example: "Open link in...": "\u041e\u0442\u0432\u0430\u0440\u044f\u043d\u0435 \u043d\u0430 \u0445\u0438\u043f\u0435\u0440\u0432\u0440\u044a\u0437\u043a\u0430 \u0432...",
Is missing in file from npm.

**Comment by mklkj** [comment]
This package contains language files for tinymce v4 and v5. For version 5, you should use files from the `langs5` directory: https://github.com/mklkj/tinymce-i18n/blob/bc12ba8/langs5/bg_BG.js#L154

**Comment by dakur** [comment]
It seems like confusing. Would not it be better to remove all the stuff from v4 as it is not even officially supported? People could still find it tagged and v5 will reside in `langs` without any confusion..

**Comment by yunay** [comment]
> This package contains language files for tinymce v4 and v5. For version 5, you should use files from the `langs5` directory: https://github.com/mklkj/tinymce-i18n/blob/bc12ba8/langs5/bg_BG.js#L154

Thanks! My mistake.
