### ISSUE TITLE
Ellipsis are added at the end of option labels resulting in translations (by tinymce-i18n) not working for them.

### ISSUE THREAD

**Issue by maciejSas** [mklkj/tinymce-i18n#8]
![image](https://user-images.githubusercontent.com/78368247/171815839-97663acd-3faa-442f-9e58-f1c348cd6957.png)
![image](https://user-images.githubusercontent.com/78368247/171815853-53e41053-2f4d-4e26-af68-d637fc69b255.png)

All options are translated, but dropdown options with ellipsis added to them are not translated.

Im using this language pack https://cdn.jsdelivr.net/webjars/org.webjars.npm/tinymce-i18n/22.2.11/langs/es.js

Translations for those labels exist in file above.

Using tinymce 5.0.7 as an artifact from org.webjars.bowergithub.tinymce

**Comment by mklkj** [comment]
You are using wrong translation file. For tinymce 5 there is langs**5** catalog, so you shuld use https://cdn.jsdelivr.net/webjars/org.webjars.npm/tinymce-i18n/22.2.11/langs5/es.js instead
